### ISSUE TITLE
Using spaces for authorized-users breaks the action

### ISSUE THREAD

**Issue by zupo** [namespacelabs/breakpoint-action#4]
If I use `authorized-users: foo, bar, bam` the action breaks with
`Error: failed to fetch SSH keys for GitHub user " bar": unexpected status code 404`. 

Using `authorized-users: foo,bar,bam` works fine.

**Comment by zupo** [comment]
~Bah, I was using an old version, no longer the case in v.0.0.5.~

Confirmed this is still the case in v.0.0.5.

**Comment by hugosantos** [comment]
Thank you for reporting, we'll look into it.

**Comment by edganiukov** [comment]
Hi @zupo ,
Fixed in the latest release (v0.0.7). You can also use `v0` tag as it points to the latest release.
