### ISSUE TITLE
Are the permissions required?

### ISSUE THREAD

**Issue by jonashaag** [namespacelabs/breakpoint-action#5]
```
    permissions:
      id-token: write
      contents: read
```

Are those required and if so why?

**Comment by hugosantos** [comment]
Hi! “contents: read” is the default; “id-token” is required to obtain a token from github to identify the workload, which is the used by breakpoint to authenticate the session to rendezvous — the server that provides the reverse tunnel capability.

If you prefer to not require Github based authentication, you can run your own rendezvous server—it’s open source and also available in namespacelabs/breakpoint.

**Comment by jonashaag** [comment]
Thank you!

I wonder why mxschmitt/action-tmate does not require any permissions.

**Comment by hugosantos** [comment]
They operate under a different threat model perhaps.

Our shared rendezvous server which enables the reverse tunneling does not have the ability to introspect encrypted connections, as the end to end encrypted nature of ssh is retained. But to use the shared rendezvous server you must be running out of a github based workflow, as we defer certain parts of abuse management to GitHub. And the way to prove you are running in an action, is to present cryptographically provable authentication material. Which is what these permissions allow us to obtain.
